spring:
  profiles:
    active: test
  application:
    name: springai-demo
  template:
    provider:
      character-encoding: UTF-8
  output:
    ansi:
      enabled: ALWAYS 
  ai:
    openai:
      api-key: sk-hzupjaizrzbdmzzdaejsxhqnlbvsrbaiqfbmrrpzvdobcdyl
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: zai-org/GLM-4.6V
          # model: zai-org/GLM-4.5-Air
          # model: Qwen/Qwen3-VL-32B-Thinking
          # model: deepseek-ai/DeepSeek-V3.2
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
  datasource:
    url: jdbc:mysql://localhost:3306/springai_demo?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
env:
  file:
    encoding: UTF-8