spring:
  datasource:
    url: jdbc:postgresql://47.118.23.183:5432/test
#    url: jdbc:postgresql://localhost:5432/test

    hikari:
      initialization-fail-timeout: -1

  ai:
    siliconflow:
      rerank:
        api-key: sk-tlnpsktyxjqqaxkfjanxsgyzhdgmjssjoapiwcnfkixirwaj
    vectorstore:
      pgvector:
        initialize-schema: false
        table-name: rag_chunks
        schema-name: public
        id-type: text
# Prompt 配置默认值
prompt:
  defaults:
    persona: 测试默认角色
    channel: 测试渠道