spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: zAzHHplnxXb7QvT02QMl0oPV
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
  sql:
    init:
      mode: never
  ai:
    dashscope:
      api-key: test-dashscope-key
    siliconflow:
      api-url: https://api.siliconflow.cn/v1/embeddings
      api-key: sk-fvkljvsojrgknsnqftkpnjoxfqvjijitspsvalywcfblvhim
      model: Qwen/Qwen3-Embedding-8B
      encoding-format: float
      dimensions: 1536
    vectorstore:
      pgvector:
        initialize-schema: true
