spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: zAzHHplnxXb7QvT02QMl0oPV
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
  sql:
    init:
      mode: never
  ai:
    dashscope:
      api-key: test-dashscope-key
    siliconflow:
      api-url: https://api.siliconflow.cn/v1/embeddings
      api-key: sk-fvkljvsojrgknsnqftkpnjoxfqvjijitspsvalywcfblvhim
      model: Qwen/Qwen3-Embedding-8B
      encoding-format: float
      dimensions: 1536
    generic-chat:
      api-url: https://api.siliconflow.cn/v1/chat/completions
      api-key: sk-fvkljvsojrgknsnqftkpnjoxfqvjijitspsvalywcfblvhim
      model: deepseek-ai/DeepSeek-R1
      temperature: 0.7
      top-p: 0.7
      top-k: 50
      max-tokens: 4096
      frequency-penalty: 0.0
      n: 1
      stream: false
      enable-thinking: false
      thinking-budget: 4096
      connect-timeout: PT5S
      read-timeout: PT20S
    vectorstore:
      pgvector:
        initialize-schema: true
