spring:
  application:
    name: spring-ai-alibaba-demo
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:}
      chat:
        options:
          model: qwen-plus
          temperature: 0.8

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
